# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('picture', models.URLField()),
                ('linkedin', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('dribbble', models.URLField(null=True)),
                ('behance', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.URLField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('website', models.URLField(null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative')),
            ],
        ),
        migrations.AddField(
            model_name='creativemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Organization'),
        ),
        migrations.AddField(
            model_name='creativemessage',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative'),
        ),
    ]
