# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('picture', models.URLField()),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('dribbble', models.CharField(blank=True, max_length=200, null=True)),
                ('behance', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.URLField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='creativemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Organization'),
        ),
        migrations.AddField(
            model_name='creativemessage',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Creative'),
        ),
    ]
