# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
