# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20160409_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='behance',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='dribbble',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='picture',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
